superpy_product_range = [
    'Fish', 
    'Quinoa', 
    'Brown beans',
    'Bread', 
    'Bulgur',
    'lettuce', 
    'White beans', 
    'Cheese', 
    'Apple', 
    'Beetroot', 
    'Kiwi', 
    'onion', 
    'Eggs', 
    'Bananas', 
    'Oats', 
    'Milk', 
    "Apples",
    "Bananas",
    "Oranges",
    "Tomatoes",
    "Carrots",
    "Potatoes",
    "Onions",
    "Milk",
    "Eggs",
    "Cheese",
    "Yogurt",
    "Chicken breasts",
    "Salmon fillets",
    "Canned tuna",
    "Pasta",
    "Rice",
    "Bread",
    "Butter",
    "Sugar",
    "Coffee",
    "Tea bags",
    "Soft drinks",
    "Bottled water",
    "Chips",
    "Chocolate bars",
    "Cookies",
    "Toilet paper",
    "Paper towels",
    "Laundry detergent"
]