superpy_product_range = [
    'Fish', 
    'Quinoa', 
    'Brown beans',
    'Bread', 
    'Bulgur',
    'lettuce', 
    'White beans', 
    'Cheese', 
    'Apple', 
    'Beetroot', 
    'Kiwi', 
    'onion', 
    'Eggs', 
    'Bananas', 
    'Oats', 
    'Milk', 
    "Apples",
    "Bananas",
    "Oranges",
    "Tomatoes",
    "Carrots",
    "Potatoes",
    "Onions",
    "Milk",
    "Eggs",
    "Cheese",
    "Yogurt",
    "Chicken breasts",
    "Salmon fillets",
    "Canned tuna",
    "Pasta",
    "Rice",
    "Flower",
    "Butter",
    "Sugar",
    "Coffee",
    "Tea bags",
    "Soft drinks",
    "Bottled water",
    "Chips",
    "Chocolate bars",
    "Cookies",
    "Toilet paper",
    "Paper towels",
    "Laundry detergent",
    "Organic Cage-Free Pasture-Raised Eggs",
    "Whole Wheat Reduced Fat Multigrain Bread",
    "Wild-Caught Alaskan Salmon",
    "Grass-Fed Beef Patties",
    "Organic Quinoa Pasta with Kale and Pesto",
    "Fair Trade Dark Chocolate Coconut Coffee",
    "Cold-Brewed Unsweetened Nitro Coffee",
    "Non-GMO Gluten-Free Dairy-Free Organic Protein Powder",
    "Plant-Based Meatless Burger Patties",
    "Sustainable Seafood Breaded Fish Sticks",
    "Whole Food Plant-Based Meal Replacement Shake",
    "Keto-Friendly Low-Carb High-Protein Snack Bar",
    "Prebiotic Probiotic Organic Greek Yogurt",
    "Cold-Pressed Extra Virgin Olive Oil with Lemon and Garlic"
]